### ISSUE TITLE
Selling not working

### ISSUE THREAD

**Issue by dcts** [dcts/radix.meme#162]
When buying a token for 100 XRD I get ~46k tokens back. 

When I then sell the 46k tokens, I get 0 XRD back. 

Here are the **TX manifests:**
```txt
# BUY
buy tx manifest: 
    CALL_METHOD Address("account_tdx_2_128t0tnge6cvufl8rc2nj6ushlamuk4fcl4ll889v4fhv57algulas9") "withdraw" Address("resource_tdx_2_1tknxxxxxxxxxradxrdxxxxxxxxx009923554798xxxxxxxxxtfd2jc") Decimal("100");
    TAKE_ALL_FROM_WORKTOP Address("resource_tdx_2_1tknxxxxxxxxxradxrdxxxxxxxxx009923554798xxxxxxxxxtfd2jc") Bucket("tx_bucket");
    CALL_METHOD Address("component_tdx_2_1cpljyu6zkdn4j2c6nl6vt9d7alf5hunadsdz8gnt72qxqg90ycdxku") "buy" Bucket("tx_bucket");
    CALL_METHOD Address("account_tdx_2_128t0tnge6cvufl8rc2nj6ushlamuk4fcl4ll889v4fhv57algulas9") "try_deposit_batch_or_abort" Expression("ENTIRE_WORKTOP") None;
    
# SELL
sell tx manifest: 
    CALL_METHOD Address("account_tdx_2_128t0tnge6cvufl8rc2nj6ushlamuk4fcl4ll889v4fhv57algulas9") "withdraw" Address("resource_tdx_2_1th7va3phvpsnw50pdf3j370ty968j66hf03mmp9tvdt9cju5jd7jrv") Decimal("46415");
    TAKE_ALL_FROM_WORKTOP Address("resource_tdx_2_1th7va3phvpsnw50pdf3j370ty968j66hf03mmp9tvdt9cju5jd7jrv") Bucket("tx_bucket");
    CALL_METHOD Address("component_tdx_2_1cpljyu6zkdn4j2c6nl6vt9d7alf5hunadsdz8gnt72qxqg90ycdxku") "sell" Bucket("tx_bucket");
    CALL_METHOD Address("account_tdx_2_128t0tnge6cvufl8rc2nj6ushlamuk4fcl4ll889v4fhv57algulas9") "try_deposit_batch_or_abort" Expression("ENTIRE_WORKTOP") None;
```

There are both transactions on stokenet dashboard:
- [buy transaction](https://stokenet-dashboard.radixdlt.com/transaction/txid_tdx_2_15yp9948hpx7nn7q0hge0rm5d8fa3tpcy2sup9sx3kf43nlpkl6rqyd79y8/summary)
- [sell transaction](https://stokenet-dashboard.radixdlt.com/transaction/txid_tdx_2_186aces6452nx27x6uzlxntjz4c9ta4pg8t68rv28rk0rz7umg5rq2jswk3/summary)

### Its amazing that the wallet shows you this, so even with a bug the user would still see that something is off:

<img width="300" src="https://github.com/user-attachments/assets/922689a1-f088-4f0b-8128-e0f711ec572f" />
<img width="300" src="https://github.com/user-attachments/assets/55bed198-b605-40a1-a91a-db2d5e53502f" />

**Comment by fliebenberg** [comment]
I have rolled out a new component that should hopefully fix this bug.
New component: component_tdx_2_1cq5mvvmtr7xq90c5nkyxrlzdd2genzu9cdlv4q9mfjd8zslagat8lx
New dapp def account for the component: account_tdx_2_1cx6gtvkqujyzn520melqnfn6cgg8g5ukvsgleup0mz2zcnymq5lnup

**Comment by fliebenberg** [comment]
Not closing yet as I just want to wait for someone to double check that the issue has been fixed.

**Comment by dcts** [comment]
This still doesnt work for me, see tx manifest here:
```
sell tx manifest: 
    CALL_METHOD Address("account_tdx_2_128t0tnge6cvufl8rc2nj6ushlamuk4fcl4ll889v4fhv57algulas9") "withdraw" Address("resource_tdx_2_1tk3ane9t6q0mhf64vwdevh74djwpuwxma25lvn72gatkf334l9ga4g") Decimal("66000");
    TAKE_ALL_FROM_WORKTOP Address("resource_tdx_2_1tk3ane9t6q0mhf64vwdevh74djwpuwxma25lvn72gatkf334l9ga4g") Bucket("tx_bucket");
    CALL_METHOD Address("component_tdx_2_1cqyxn8u3k5qwlhycdfr7au4hmseugjfsyv8ge5yje9xhwq0pn9phan") "sell" Bucket("tx_bucket");
    CALL_METHOD Address("account_tdx_2_128t0tnge6cvufl8rc2nj6ushlamuk4fcl4ll889v4fhv57algulas9") "try_deposit_batch_or_abort" Expression("ENTIRE_WORKTOP") None;
```

<img width=300 src="https://github.com/user-attachments/assets/95ed7064-95c2-4449-81fc-9453f7571a3e" />

And this is the tx:
https://stokenet-dashboard.radixdlt.com/transaction/txid_tdx_2_1ragkyqre7xwlk3lwjc23mqj487v8q3wg7zn8hd0q3s3sj8wxdaaq5p9q5h/summary

**Comment by fliebenberg** [comment]
Should be fixed by new component: component_tdx_2_1cqxv84t8tya5q0rwasdlwyu57cyw9x52trsgfqarjfc0yx0f4980g7
Please test and confirm it is working before we close this.

**Comment by dcts** [comment]
This was resolved and works now as expected!
